### ISSUE TITLE
Any chance of changing the fontFamily on the keypad?

### ISSUE THREAD

**Issue by jet2018** [talut/react-native-pin-view#64]
Currently, we are using this feature on our login screen but the app has its defined fontFamily. I tried adding this font like below, but I was not successful.

```css
buttonTextStyle={{
          color: colors[theme],
          fontFamily: fonts.awash_100,
        }}
```
The buttons don't take the font up.
